### ISSUE TITLE
opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP

### ISSUE THREAD

**Issue by datmospro** [freeconga/congatudo-add-on#25]
Hi,

Sorry i must open another Issue, i think related with the las one.

I did 3 Full Cleans, and never get the segments. After this last full clean, i tried to do a "GoTo" coordinates, and recived this error:
```
[2021-12-30T16:41:30.111Z] [WARN] Error while starting goTo coordinates {
  body: { action: 'goto', coordinates: { x: 482, y: 481 } },
  e: DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP'
      at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1181:16)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    metadata: undefined
```

I dont really understand, but it seems there is some problem with the map stored on the robot?

Thanks!

**Comment by datmospro** [comment]
Also, i'm having a lot of problems to acces de Web UI, i must do like 40 updates to acces, and sometimes the addons ShutDown showing this:

```
<--- Last few GCs --->
[205:0x747361f0]  1994130 ms: Scavenge 28.8 (31.5) -> 28.3 (31.5) MB, 0.9 / 0.0 ms  (average mu = 0.919, current mu = 0.918) allocation failure 
[205:0x747361f0]  1994705 ms: Mark-sweep 31.2 (34.0) -> 30.5 (34.0) MB, 531.0 / 0.5 ms  (average mu = 0.810, current mu = 0.612) allocation failure scavenge might not succeed
[205:0x747361f0]  1995336 ms: Mark-sweep 31.1 (34.0) -> 30.8 (34.2) MB, 522.4 / 0.1 ms  (average mu = 0.654, current mu = 0.172) allocation failure scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
./valetudo.sh: line 54:   205 Aborted                 (core dumped) valetudo
[cmd] dumb-init exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by txitxo0** [comment]
> Hi,
> 
> Sorry i must open another Issue, i think related with the las one.
> 
> I did 3 Full Cleans, and never get the segments. After this last full clean, i tried to do a "GoTo" coordinates, and recived this error:
> 
> ```
> [2021-12-30T16:41:30.111Z] [WARN] Error while starting goTo coordinates {
>   body: { action: 'goto', coordinates: { x: 482, y: 481 } },
>   e: DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP'
>       at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1181:16)
>       at listOnTimeout (node:internal/timers:557:17)
>       at processTimers (node:internal/timers:500:7) {
>     metadata: undefined
> ```
> 
> I dont really understand, but it seems there is some problem with the map stored on the robot?
> 
> Thanks!

I guess you already have the solution, but try calling to the endpoint in charge of pending maps ;)

**Comment by txitxo0** [comment]
> Also, i'm having a lot of problems to acces de Web UI, i must do like 40 updates to acces, and sometimes the addons ShutDown showing this:
> 
> ```
> <--- Last few GCs --->
> [205:0x747361f0]  1994130 ms: Scavenge 28.8 (31.5) -> 28.3 (31.5) MB, 0.9 / 0.0 ms  (average mu = 0.919, current mu = 0.918) allocation failure 
> [205:0x747361f0]  1994705 ms: Mark-sweep 31.2 (34.0) -> 30.5 (34.0) MB, 531.0 / 0.5 ms  (average mu = 0.810, current mu = 0.612) allocation failure scavenge might not succeed
> [205:0x747361f0]  1995336 ms: Mark-sweep 31.1 (34.0) -> 30.8 (34.2) MB, 522.4 / 0.1 ms  (average mu = 0.654, current mu = 0.172) allocation failure scavenge might not succeed
> <--- JS stacktrace --->
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> ./valetudo.sh: line 54:   205 Aborted                 (core dumped) valetudo
> [cmd] dumb-init exited 134
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> ```

The logs says something about the memory, check if your machine is too "small" to support all your environment ;)

**Comment by adrigzr** [comment]
@datmospro have you been able to address the issue? Did you accept the pending map after a full clean to store the segments? This feature is not documented and you need to access the Valetudo swagger in order to accept it.

**Comment by datmospro** [comment]
All this problems was using the plugin Congatudo, i can't resolve them. With the plugin i can't acces de swagger menu and do the stuff.

So i installed Valetudo on the Conga and now i can save the maps to create the segments, the web UI does not give me problems to load it and everything is working fine.

My problem was with Congatudo plugin, and a Conga without Valetudo, i didn't tested if Congatudo + Conga with Valutdo works or not.

Thanks guys !!

**Comment by txitxo0** [comment]
You are able to access to swagger just providing a port in the addon configuration for the webui host
