### ISSUE TITLE
Problem with map saving

### ISSUE THREAD

**Issue by davidbrines** [freeconga/congatudo-add-on#30]
The conga starts to create the map fine, but when it is finishing, the map changes and an offset map with horizontal lines appears.

In addition, neither the position of the conga nor its path can be seen.

![image](https://user-images.githubusercontent.com/97938875/156004035-2ba720af-e5c5-4968-a413-c7bfb1488c00.png)

**Comment by txitxo0** [comment]
This issue should be open in the valetudo repo, 
Anyhow, do you test with the original cecotec app if the problem persists?

https://github.com/freeconga/Valetudo
