### ISSUE TITLE
3890 not working, missing DNS records?

### ISSUE THREAD

**Issue by joao-bel-bynd** [freeconga/congatudo-add-on#36]
I follow all steps of the guide and I still can connect my conga to HA, maybe is missing some dns records but not sure.
at the moment my DNS on the robot 
`192.168.1.174 cecotec.das.3irobotix.net cecotec.download.3irobotix.net cecotec.log.3irobotix.net cecotec.ota.3irobotix.net eu.das.3irobotics.net eu.log.3irobotics.net eu.ota.3irobotics.net`

If I ping any of the cecotec DNS, 192.168.1.174 is my HA ip.
```
PING cecotec.das.3irobotix.net (192.168.1.174): 56 data bytes
64 bytes from 192.168.1.174: seq=0 ttl=64 time=8.056 ms
64 bytes from 192.168.1.174: seq=1 ttl=64 time=4.203 ms
64 bytes from 192.168.1.174: seq=2 ttl=64 time=2.076 ms
64 bytes from 192.168.1.174: seq=3 ttl=64 time=2.072 ms
64 bytes from 192.168.1.174: seq=4 ttl=64 time=2.166 ms
64 bytes from 192.168.1.174: seq=5 ttl=64 time=2.090 ms
64 bytes from 192.168.1.174: seq=6 ttl=64 time=2.063 ms
```

The robot is still online on the conga 3890 APP so not sure what I'm missing...

**Comment by txitxo0** [comment]
The 3890 model is not yet supported. 

You are free to koin to the already open discussion trying to get into this model protocol
https://github.com/adrigzr/agnoc/issues/40
